ai_flow_plugins/blob_manager_plugins/oss_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_oss_blob_manager.py
lib/airflow/airflow/task/task_runner/standard_task_runner.py

Fix oss blob manager download concurrently (#2)
- [Airflow] StandardTaskRunner log exception when fail 
- [AIFlow] Fix oss blob manager download concurrently

[AIFlow] Fix oss blob manager download concurrently

---

bin/init-airflow-env.sh
bin/init-airflow-with-celery-executor.sh
bin/start-airflow.sh
bin/start-all-aiflow-services.sh
bin/stop-airflow.sh
lib/airflow/airflow/cli/cli_parser.py
lib/airflow/airflow/cli/commands/webserver_command.py
lib/airflow/airflow/config_templates/default_airflow.cfg
lib/airflow/airflow/config_templates/default_test.cfg
lib/airflow/airflow/configuration.py
lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py

[Airflow]Refactor airflow scripts.

[Airflow]Refactor airflow scripts.

---

bin/start-all-aiflow-services.sh
bin/stop-airflow.sh

[AIFlow]1. The start-all-aiflow-services.sh removes duplicate init. 2. The stop-airflow.sh removes the call init script.

[AIFlow]Remove duplicate init

---

bin/init-aiflow-env.sh
bin/start_aiflow.py
bin/stop-aiflow.sh
lib/notification_service/bin/init-notification-env.sh
lib/notification_service/bin/start-notification.sh
lib/notification_service/bin/start_notification_server.py
lib/notification_service/bin/start_notification_service.py
lib/notification_service/bin/stop-notification.sh

Init script generate default configuration
Init script generate default configuration

[bin] Init script generate default configuration

---

examples/sklearn_examples/workflows/batch_train_stream_predict/batch_train_stream_predict.py
examples/sklearn_examples/workflows/batch_train_stream_predict/batch_train_stream_predict_executor.py

[AIFlow] Uses the sklearn batch train & stream predict example for quick start

---

bin/init-airflow-env.sh
bin/init-airflow-with-celery-executor.sh
bin/start-airflow.sh
bin/start-all-aiflow-services.sh
bin/stop-airflow.sh
lib/airflow/airflow/cli/cli_parser.py
lib/airflow/airflow/cli/commands/webserver_command.py
lib/airflow/airflow/config_templates/default_airflow.cfg
lib/airflow/airflow/config_templates/default_test.cfg
lib/airflow/airflow/configuration.py
lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py

Refactor airflow scripts.
cherry-pick :
1.  https://github.com/flink-extended/ai-flow/pull/62
2. https://github.com/flink-extended/ai-flow/pull/67

[Airflow]Refactor airflow scripts. (#62#67)

---

ai_flow/frontend/web_server.py
ai_flow_plugins/scheduler_plugins/airflow/dag_generator.py
ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.py
lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
lib/airflow/airflow/models/dag.py
lib/airflow/airflow/models/dagrun.py

Fix periodic workflow cannot run. #52 
Fix periodic workflow cannot run

[bugfix] Fix periodic workflow cannot run

---

ai_flow_plugins/blob_manager_plugins/s3_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_s3_blob_manager.py
requirements.txt

The S3 storage is common case in many companies like NetEase etc, and `BlobManager` should support S3 storage backend. It's necessary to introduce the S3 `BlobManager` implementation. Fix #58

[Plugins] Introduces the S3 BlobManager implementation

---

chart/templates/_helpers.yaml
chart/templates/aiflow_webserver/webserver-deployment.yaml
chart/templates/configmaps/aiflow-configmaps.yaml
chart/templates/notification/notifiaction-svc.yaml
chart/templates/notification/notification-deployment.yaml
chart/values.yaml

Update helm chart to accommodate the new configuration.
Update helm chart to accommodate the new configuration.
Manually tested.

[chart] Update helm chart to accommodate new configuration

---

ai_flow_plugins/blob_manager_plugins/hdfs_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_hdfs_blob_manager.py

Fix HDFSBlobManager failed to download existed file
- Fix HDFSBlobManager failed to download existed file
- Fix concurrently download bug.

[AI Flow] Fix HDFSBlobManager failed to download existed file

---

docs/content/deployment/installation.md
docs/content/get_started/about.md

Improve installation doc

---

.gitignore
ai_flow/config_templates/default_aiflow_server.yaml
docs/content/deployment/deploying_aiflow_server.md
docs/content/deployment/deploying_notification_server.md
docs/content/deployment/deploying_scheduler.md
docs/content/deployment/index.md
docs/content/deployment/overview.md
lib/notification_service/notification_service/config_templates/default_notification_server.yaml

Add deployment docs
Add deployment docs

[docs] Add deployment docs

---

lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py

Replace unnecessary assertion with warning
- Replace unnecessary assertion with warning

[Scheduler] Replace unnecessary assertion with warning

---

ai_flow/config_templates/default_aiflow_server.yaml
docs/content/get_started/quickstart.md

Add docs of docker support in quickstart.md
- Change default aiflow web server host to 0.0.0.0
- Add docs of docker support in quickstart.md

[Doc] Add docs of docker support in quickstart

---

ai_flow/__init__.py
ai_flow/api/ops.py

[AIFlow] Removes the uncompleted api action_on_dataset_event

---

docs/content/deployment/deploying_aiflow_server.md
docs/content/deployment/deploying_scheduler.md
lib/airflow/airflow/config_templates/default_airflow.cfg

Add deployment documentation about CeleryExecutor
Add deployment documentation about CeleryExecutor

[Doc] Add deployment documentation about CeleryExecutor

---

docs/content/get_started/concept.md
docs/content/get_started/concepts.md
docs/content/get_started/index.md

[Document]Add concepts.md.

---

ai_flow_plugins/blob_manager_plugins/hdfs_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_hdfs_blob_manager.py
bin/init-airflow-with-celery-executor.sh
docker-compose.yaml
examples/celery/project.yaml
lib/airflow/airflow/config_templates/default_airflow.cfg
lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py

Cherry pick to release-0.2
- Make new scripts work within Docker Compose (#88)
- [Scheduler] Replace unnecessary assertion with warning (#101)
- [AI Flow] Fix HDFSBlobManager failed to download existed file (#87)

Cherry pick to release-0.2

---

requirements.txt

Fix WTForms version in requirements.txt #121 
[AIFlow] Fix WTForms version in requirements.txt

[AIFlow] Fix WTForms version in requirements.txt

---

docs/content/deployment/installation.md
docs/content/get_started/quickstart.md
docs/content/workflow_development/sdk_installation.md

Improve documentation about installation
- docs/content/deployment/installation.md
- docs/content/get_started/quickstart.md
- docs/content/workflow_development/sdk_installation.md

[Doc] Improve documentation about installation

---

ai_flow/java/client/pom.xml
ai_flow/java/pom.xml
lib/notification_service/java/pom.xml
lib/notification_service/setup.py
pom.xml
requirements.txt
setup.py

Commit for release 0.2.2
- Commit for release 0.2.2

Commit for release 0.2.2

---

ai_flow/__init__.py
ai_flow/api/ai_flow_context.py
ai_flow/common/configuration.py
ai_flow/workflow/workflow_config.py
examples/notebook/simple_workflow.ipynb

[AIFlow] Supports the workflow development on the Jupyter Notebook

---

lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py

Fix PeriodicEvent handling
Fix PeriodicEvent handling

[Airflow] Fix PeriodicEvent handling

---

lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py

fix #155 
add judge for dunruns length

[Bugfix] Fix in dagruns IndexError when dagruns are empty

---

ai_flow/__main__.py
ai_flow/cli/__init__.py
ai_flow/cli/cli_parser.py
ai_flow/cli/commands/__init__.py
ai_flow/cli/commands/version_command.py
ai_flow/test/cli/__init__.py
ai_flow/test/cli/commands/__init__.py
ai_flow/test/cli/commands/test_version_command.py
ai_flow/test/cli/test_cli_parser.py
ai_flow/test/common/test_module_load.py
ai_flow/util/helpers.py
setup.py

Support command line interface
- Support command line interface

Add aiflow cli infra

---

lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py

Import warning log content in #156 .
Import warning log content and update test case.

[Airflow] Improve warning log when no dag runs for `PeriodicEvent`

---

ai_flow/metadata_store/utils/ProtoToMeta.py
ai_flow/test/endpoint/test_client.py

Bugfix the properties field convert of the ProtoToMeta. Fix #167

[AIFlow] Bugfix the properties field convert of the `ProtoToMeta`

---

lib/airflow/airflow/providers/amazon/aws/log/cloudwatch_task_handler.py
lib/airflow/airflow/providers/amazon/aws/log/s3_task_handler.py
lib/airflow/airflow/providers/amazon/get_provider_info.py
lib/airflow/airflow/providers/celery/get_provider_info.py
lib/airflow/airflow/providers/elasticsearch/get_provider_info.py
lib/airflow/airflow/providers/elasticsearch/log/es_task_handler.py
lib/airflow/airflow/providers/ftp/get_provider_info.py
lib/airflow/airflow/providers/google/cloud/log/gcs_task_handler.py
lib/airflow/airflow/providers/google/cloud/log/stackdriver_task_handler.py
lib/airflow/airflow/providers/google/get_provider_info.py
lib/airflow/airflow/providers/http/get_provider_info.py
lib/airflow/airflow/providers/imap/get_provider_info.py
lib/airflow/airflow/providers/microsoft/azure/get_provider_info.py
lib/airflow/airflow/providers/microsoft/azure/log/wasb_task_handler.py
lib/airflow/airflow/providers/sqlite/get_provider_info.py
lib/airflow/tests/providers/amazon/aws/log/test_cloudwatch_task_handler.py
lib/airflow/tests/providers/amazon/aws/log/test_s3_task_handler.py
lib/airflow/tests/providers/elasticsearch/log/test_es_task_handler.py
lib/airflow/tests/providers/google/cloud/log/test_gcs_task_handler.py
lib/airflow/tests/providers/google/cloud/log/test_stackdriver_task_handler.py
lib/airflow/tests/providers/microsoft/azure/log/test_wasb_task_handler.py

Append other remote log handler that not included in #174 
* ES task handler
* stackdriver task handler
* cloudwath task handler
This change is already covered by existing tests, update the old test case in airlfow provider tests.

Append other remote log handler that not included in #174 

---

ai_flow/alembic.ini
ai_flow/cli/cli_parser.py
ai_flow/cli/commands/db_command.py
ai_flow/endpoint/server/server.py
ai_flow/endpoint/server/server_config.py
ai_flow/migrations/__init__.py
ai_flow/migrations/env.py
ai_flow/migrations/script.py.mako
ai_flow/migrations/versions/0e8fefcce376_add_workflow_snapshot.py
ai_flow/migrations/versions/__init__.py
ai_flow/migrations/versions/de045f309236_add_aiflow_member.py
ai_flow/migrations/versions/de1c96ef582a_add_ai_flow_tables.py
ai_flow/store/db/db_util.py
ai_flow/store/sqlalchemy_store.py
ai_flow/test/api/test_ai_flow_context.py
ai_flow/test/cli/aiflow_server.yaml
ai_flow/test/cli/commands/test_db_command.py
ai_flow/test/endpoint/server/aiflow_server.yaml
ai_flow/test/endpoint/server/test_server_config.py
ai_flow/test/endpoint/server/test_server_runner.py
ai_flow/test/endpoint/test_client.py
ai_flow/test/endpoint/test_high_availability.py
ai_flow/test/endpoint/test_java_client.py
ai_flow/test/endpoint/test_mysql_client.py
ai_flow/test/store/test_sqlalchemy_store.py
ai_flow/test/util/test_sqlalchemy_db.py
ai_flow/util/sqlalchemy_db.py
requirements.txt
setup.py

[AIFlow] Support database version migration.

[AIFlow] Support database version migration.

---

ai_flow/api/ai_flow_context.py
ai_flow/test/api/test_ai_flow_context.py
ai_flow/test/api/ut_workflows/workflows/test_ai_flow_context/test_ai_flow_context.py

The initialization of the notebook context has the bug for multiple initialization. Fix #185

[AIFlow] Bugfix the initialization of the notebook context

---

docs/conf.py

Set version of documentation equivalent to project version
- Set version of documentation equivalent to project version

Set version of documentation equivalent to project version

---

lib/notification_service/notification_service/cli/commands/server_command.py
lib/notification_service/notification_service/util/utils.py
lib/notification_service/tests/cli/commands/test_server_command.py
lib/notification_service/tests/util/test_util.py

Improve notification server cli
- [Notification] Notification server stop check if process exit
- [Notification] Notification server start daemon install SIGTERM handler
- [Notification] Notification server process delete pid file when exit 

[Notification] Improve notification server cli

---

ai_flow/cli/cli_parser.py
ai_flow/cli/commands/db_command.py
ai_flow/cli/commands/server_command.py
ai_flow/cli/commands/webserver_command.py
ai_flow/endpoint/server/server_config.py
ai_flow/frontend/web_server.py
ai_flow/migrations/env.py
ai_flow/settings.py
ai_flow/test/aiflow_server.yaml
ai_flow/test/cli/commands/test_db_command.py
ai_flow/test/cli/commands/test_server_command.py
ai_flow/test/cli/commands/test_webserver_command.py
ai_flow/test/test_settings.py
ai_flow/test/util/test_process_utils.py
bin/start-aiflow.sh
bin/stop-aiflow.sh

Add AIFlow server and webserver cli #171 
Add AIFlow server and webserver cli

[AIFlow] Add AIFlow server and webserver cli

---

ai_flow/cli/cli_parser.py
ai_flow/cli/commands/config_command.py
ai_flow/test/cli/commands/test_config_command.py
ai_flow/util/config_utils.py
bin/start_aiflow.py
lib/notification_service/bin/start_notification_server.py
lib/notification_service/notification_service/cli/cli_parser.py
lib/notification_service/notification_service/cli/commands/config_command.py
lib/notification_service/notification_service/util/cli.py
lib/notification_service/notification_service/util/config.py
lib/notification_service/tests/cli/commands/test_config_command.py

The config management needs to support the command line interfaces for maintenance. Fix #201 .

[AIFlow][Notification] Introduces the command line interfaces of the config

---

ai_flow/cli/cli_parser.py
docs/content/api/index.rst
docs/content/api/java/notification.md
docs/content/cli/aiflow.md
docs/content/cli/index.md
docs/content/cli/notification.md
docs/index.rst

Introduces the document of the command line interface.

[Document] Introduces the document of the command line interface

---

ai_flow/store/sqlalchemy_store.py

Update logging level of log in sqlalchemy_store.py
Update logging level of log in sqlalchemy_store.py

[AIFlow] Update logging level of log in sqlalchemy_store.py

---

ai_flow/frontend/src/views/metadata/ModelVersion.vue
ai_flow/model_center/entity/model_version_detail.py

[Frontend] Bugfix the fields of the model version list in frontend

---

chart/templates/_helpers.yaml
chart/templates/aiflow_webserver/webserver-deployment.yaml
chart/templates/configmaps/aiflow-configmaps.yaml
chart/templates/notification/notification-deployment.yaml
chart/values.schema.json
chart/values.yaml

Update chart to start services with cli and use different db
Update chart to start services with cli and use different db
Manually tested

[AIFlow][chart] Update chart to start services with cli and use different db

---

lib/notification_service/bin/init-notification-env.sh
lib/notification_service/bin/start-notification.sh
lib/notification_service/bin/stop-notification.sh
lib/notification_service/notification_service/cli/commands/server_command.py
lib/notification_service/notification_service/util/db.py
lib/notification_service/tests/cli/commands/test_server_command.py

Make notification scripts using cli.
- Make notification scripts using cli.

[Notification] Start notification with command-line interface

---

ai_flow/util/process_utils.py
lib/notification_service/notification_service/cli/commands/server_command.py
lib/notification_service/notification_service/util/utils.py
lib/notification_service/tests/cli/commands/test_server_command.py
lib/notification_service/tests/test_high_availability.py
lib/notification_service/tests/test_notification.py
lib/notification_service/tests/util/test_util.py

Update notificaiton stop
Update notificaiton stop

[Notification] Update notificaiton stop

---

ai_flow/test/util/server_util.py
lib/airflow/tests/contrib/jobs/test_scheduler_client.py

Add timeout to test cases of scheduler client
- Add timeout to test cases of scheduler client

Add timeout to test cases of scheduler client

---

ai_flow/java/client/pom.xml
ai_flow/java/pom.xml
ai_flow/version.py
lib/notification_service/java/pom.xml
lib/notification_service/notification_service/version.py
pom.xml

Bump version to 0.4.dev0
- Bump version to 0.4.dev0

Bump version to 0.4.dev0

---

lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
lib/airflow/airflow/contrib/jobs/periodic_manager.py
lib/airflow/tests/contrib/jobs/it_test_event_based_scheduler.py

[Airflow] Solve the bug that does not stop periodic task scheduling.

[Airflow] Solve the bug that does not stop periodic task scheduling.

---

lib/airflow/airflow/contrib/jobs/scheduler_client.py
lib/airflow/tests/contrib/jobs/test_scheduler_client.py

[Airflow] The scheduler client adds timeout mechanism by default.

[Airflow] The scheduler client adds timeout mechanism by default.

---

ai_flow/client/__init__.py
ai_flow/client/ai_flow_client.py
ai_flow/client/notification_client.py
ai_flow/context/job_context.py
ai_flow/java/client/pom.xml
ai_flow/java/client/src/main/java/org/aiflow/client/AIFlowClient.java
ai_flow/java/client/src/test/java/org/aiflow/client/AIFlowClientTest.java
ai_flow/java/pom.xml
ai_flow/test/cli/commands/test_job_command.py
ai_flow/test/cli/commands/test_workflow_command.py
ai_flow/test/client/__init__.py
ai_flow/test/client/test_notification_client.py
ai_flow/test/endpoint/test_client.py
ai_flow/test/endpoint/test_high_availability.py
ai_flow/test/endpoint/test_java_client.py
ai_flow/test/endpoint/test_mysql_client.py

[AIFlow] Refactor the AIFlowClient.

[AIFlow] Refactor the AIFlowClient.

---

ai_flow/endpoint/client/metadata_client.py
ai_flow/endpoint/client/model_center_client.py
ai_flow/endpoint/server/server.py
ai_flow/java/client/pom.xml
ai_flow/java/client/src/main/java/org/aiflow/client/AIFlowClient.java
ai_flow/java/client/src/main/java/org/aiflow/client/MetadataClient.java
ai_flow/java/client/src/main/java/org/aiflow/client/ModelCenterClient.java
ai_flow/java/client/src/main/java/org/aiflow/client/entity/ModelVersion.java
ai_flow/java/client/src/test/java/org/aiflow/client/AIFlowClientTest.java
ai_flow/java/pom.xml
ai_flow/metadata_store/service/service.py
ai_flow/model_center/service/service.py
ai_flow/project/project_config.py
ai_flow/test/endpoint/test_client.py
ai_flow/test/endpoint/test_high_availability.py
ai_flow/test/endpoint/test_mysql_client.py

[AIFlow]Place the sent message on the client side.

[AIFlow]Place the sent message on the client side.

---

ai_flow/scheduler_service/service/service.py
ai_flow_plugins/scheduler_plugins/airflow/ai_flow_operator.py
ai_flow_plugins/tests/it_workflows/workflows/test_action_on_event/test_action_on_event.py
examples/sklearn_examples/workflows/batch_train_stream_predict/batch_train_stream_predict_executor.py
examples/workflow_on_event/workflows/hourly_preprocess_workflow/hourly_preprocess_workflow.py

Extract zip file to specific path to avoid conflict
- Add ut_worflow to CI
- Examples should use get_notification_client now
- Extract zip file to specific path to avoid conflict

Extract zip file to specific path to avoid conflict

---

ai_flow_plugins/job_plugins/flink/__init__.py
ai_flow_plugins/job_plugins/flink/flink_env.py
ai_flow_plugins/job_plugins/flink/flink_processor.py
ai_flow_plugins/job_plugins/flink/flink_run_main.py
ai_flow_plugins/job_plugins/flink/flink_version.py
ai_flow_plugins/job_plugins/flink/flink_wrapped_env.py
ai_flow_plugins/tests/job_plugins/single_job_scheduler.py
ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink_processor.py
examples/wide_and_deep/workflows/wdl/cencus_stream_train_executors.py
examples/wide_and_deep/workflows/wdl/census_batch_executors.py
requirements-dev.txt
requirements.txt
run_tests.sh

[Plugins] Flink job plugin supports the multiple Flink versions

---

ai_flow_plugins/tests/job_plugins/single_job_scheduler.py
ai_flow_plugins/tests/job_plugins/ut_workflows/__init__.py
ai_flow_plugins/tests/job_plugins/ut_workflows/master.yaml

Fix #239 
- Add tests of job_plugins to CI flow

Add tests of job_plugins to CI flow

---

.github/workflows/publish_ai_flow_image.yaml

Automatically push image with latest tag.
- Automatically push image with latest tag

Automatically push image with latest tag

---

docs/content/cli/aiflow.md

[AIFlow]Add stop/resume scheduling job to cli document.

[AIFlow]Add stop/resume scheduling job to cli document.

---

ai_flow_plugins/scheduler_plugins/airflow/ai_flow_operator.py
ai_flow_plugins/tests/it_workflows/workflows/test_python/test_python.py

[AIFlow]Fix the airflow operator context does not set correctly bug.

[AIFlow]Fix the airflow operator context does not set correctly bug.

---

examples/demo/workflows/bash/bash.py
examples/demo/workflows/bash/bash.yaml

Add Bash example

---

ai_flow_plugins/job_plugins/flink/flink_run_main.py
ai_flow_plugins/job_plugins/python/python_run_main.py

[AIFlow]Fix the bug using aiflow workflow start-execution command to run a python or a flink job has an error.

[AIFlow]Fix the bug using aiflow workflow start-execution command.

---

examples/demo/workflows/python/python.py
examples/demo/workflows/python/python.yaml

[AIFlow]Add python example.

---

ai_flow/util/serialization_utils.py
ai_flow_plugins/job_plugins/flink/flink_run_main.py
ai_flow_plugins/job_plugins/python/python_run_main.py

[AIFlow]Remove importing workflow file.

[AIFlow]Remove importing workflow file.

---

ai_flow/cli/commands/workflow_command.py
ai_flow/common/module_load.py
ai_flow/test/common/load_module_for_test.py

[AIFlow]Fix the bug: When the workflow has external dependencies, submitting the workflow will report an error。

[AIFlow]Fix the bug: When submit the workflow

---

examples/demo/workflows/flink/README.md
examples/demo/workflows/flink/flink.py
examples/demo/workflows/flink/flink.yaml
examples/demo/workflows/flink/wordcount_processor.py

[AIFlow]Add flink example.

---

ai_flow/config_templates/default_aiflow_server.yaml
docs/content/deployment/deploying_aiflow_server.md

Document the configuration of the log folder.

[Document] Document the configuration of the log folder

---

.github/workflows/flink_ai_flow_ci.yml
ai_flow_plugins/blob_manager_plugins/oss_blob_manager.py
ai_flow_plugins/blob_manager_plugins/s3_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_hdfs_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_oss_blob_manager.py
ai_flow_plugins/tests/blob_manager_plugins/test_s3_blob_manager.py
requirements.txt
setup.py

Put unnecessary dependencies to extra requirements
- Put unnecessary dependencies to extra requirements

Put unnecessary dependencies to extra requirements

---

README.md

Supports the Google Groups of the AIFlow community.

[AIFlow] Supports the Google Groups of the AIFlow community

---

docs/content/development/create_workflows.md
docs/content/development/run_workflows.md
docs/content/development/use_the_event.md
docs/content/get_started/index.md
docs/content/get_started/quickstart/in_docker.md
docs/content/get_started/quickstart/locally.md
docs/content/get_started/quickstart/run_an_example.md
docs/content/get_started/tutorial.md
docs/content/get_started/tutorials_and_examples/index.md

Refactor the structure

---

docs/content/tutorial_and_examples/tutorial.md
examples/tutorial_project/workflows/tutorial_workflow/init_env.py
examples/tutorial_project/workflows/tutorial_workflow/tutorial_workflow.py

[AIFlow]Update tutorial.md and tutorial code.

[AIFlow]Update tutorial.md and tutorial code.

---

ai_flow/endpoint/client/metadata_client.py
ai_flow/test/endpoint/test_client.py

[AIFlow]Fix register_model_version sending wrong event type bug.

[AIFlow]Fix register_model_version sending wrong event type bug.

---

docs/content/concepts.md
docs/content/development/create_a_project.md
docs/content/development/create_workflows.md
docs/content/development/index.md
docs/content/development/periodic_config.md
docs/content/how_to_guides/index.md
docs/content/how_to_guides/set_up_mysql_as_backend.md
docs/content/installation.md
docs/content/plugins/blob_manager_plugin.md
docs/content/plugins/index.md
docs/content/plugins/job_plugin.md
docs/content/plugins/scheduler_plugin.md
docs/index.rst
docs/reference/extra_packages.md

refactor development and installation

---

docs/content/get_started/quickstart/in_docker.md
docs/content/get_started/quickstart/locally.md
docs/content/how_to_guides/set_up_mysql_as_backend.md
docs/content/installation.md
examples/sklearn_examples/workflows/batch_train_stream_predict/batch_train_stream_predict.py

refactor quickstart

---

ai_flow/__init__.py
ai_flow/api/ops.py

[AIFlow]action_on_model_version_event add sender param.

[AIFlow]action_on_model_version_event add sender param.

---

CONTRIBUTING.md
README.md

Add documents about add code comments
- Add documents about add code comments

Add documents about add code comments

---

ai_flow/java/client/pom.xml
ai_flow/java/pom.xml
ai_flow/version.py
lib/notification_service/java/pom.xml
lib/notification_service/notification_service/version.py
pom.xml

*Commit for 0.3.1
- Change version.

Commit for 0.3.1

---

docs/content/get_started/quickstart/locally.md
lib/notification_service/notification_service/service.py
lib/notification_service/tests/test_service.py
setup.py

*Remove unnecessary mongo dependency
- Remove unnecessary mongo dependency

Remove unnecessary mongo dependency

---

requirements.txt

*Fix dependencies error about mongodb
- Fix dependencies error about mongodb

Fix dependencies error about mongodb

---

docs/content/get_started/quickstart/in_docker.md
docs/content/get_started/quickstart/locally.md
setup.py

Fix typo and documents of example dependencies
- Fix typo and documents of example dependencies

Fix typo and documents of example dependencies

---

Dockerfile
docs/content/get_started/quickstart/in_docker.md
docs/content/get_started/quickstart/locally.md

Install git for users in Docker
- Install git for users in Docker

Install git for users in Docker

---

.github/workflows/flink_ai_flow_ci.yml
Dockerfile
docs/content/deployment/deploying_scheduler.md
docs/reference/extra_packages.md
setup.py

Fix docker image not work in docker-compose
- Fix docker image not work in docker-compose

Fix docker image not work in docker-compose

---

.github/workflows/flink_ai_flow_ci.yml
Dockerfile
docs/content/deployment/deploying_scheduler.md
docs/reference/extra_packages.md
setup.py

Fix docker image not work in docker-compose
- Fix docker image not work in docker-compose

Fix docker image not work in docker-compose (#315)

---

MANIFEST.in
ai_flow/cli/cli_parser.py
ai_flow/cli/commands/task_execution_command.py
ai_flow/common/configuration/config_constants.py
ai_flow/common/util/cli_utils.py
ai_flow/common/util/process_utils.py
ai_flow/common/util/thread_utils.py
ai_flow/model/status.py
ai_flow/model/task_execution.py
ai_flow/scheduler/__init__.py
ai_flow/settings.py
ai_flow/task_executor/__init__.py
ai_flow/task_executor/local/__init__.py
ai_flow/task_executor/local/local_registry.py
ai_flow/task_executor/local/local_task_executor.py
ai_flow/task_executor/local/worker.py
ai_flow/task_executor/task_executor.py
ai_flow/tests/common/util/test_process_utils.py
ai_flow/tests/common/util/test_thread_utils.py
ai_flow/tests/task_executor/__init__.py
ai_flow/tests/task_executor/local/__init__.py
ai_flow/tests/task_executor/local/test_local_registry.py
ai_flow/tests/task_executor/local/test_local_task_executor.py
tests/common/configuration/test_configuration.py

- Add task executor API 
- Add local task executor implementation

Add local task executor

---

ai_flow/common/util/db_util/session.py
ai_flow/metadata/timer.py
ai_flow/migrations/versions/7edd3c063e94_add_timer_table.py
ai_flow/model/internal/events.py
ai_flow/scheduler/timer.py
tests/scheduler/__init__.py
tests/scheduler/test_timer.py

Add timer module

---

ai_flow/blob_manager/blob_manager_interface.py
ai_flow/blob_manager/impl/hdfs_blob_manager.py
ai_flow/blob_manager/impl/local_blob_manager.py
ai_flow/blob_manager/impl/oss_blob_manager.py
ai_flow/common/configuration/config_constants.py
ai_flow/common/configuration/config_templates/aiflow_client.yaml
ai_flow/task_executor/local/local_task_executor.py
tests/blob_manager/impl/test_hdfs_blob_manager.py
tests/blob_manager/impl/test_local_blob_manager.py
tests/blob_manager/impl/test_oss_blob_manager.py
tests/blob_manager/test_blob_manager_interface.py

Refactor Blob config
- Refactor Blob config

Refactor Blob config

---

ai_flow/metadata/metadata_manager.py
ai_flow/model/internal/events.py
ai_flow/scheduler/rule_extractor.py
ai_flow/scheduler/rule_wrapper.py
tests/scheduler/test_rule_extractor.py

Add rule extractor

---

ai_flow/model/operator.py
ai_flow/model/operators/bash.py
ai_flow/model/operators/python.py
tests/model/operators/test_bash_operator.py
tests/model/operators/test_python_operator.py

Add python operator
- Add python operator

Add python operator

---

ai_flow/metadata/metadata_manager.py
tests/metadata/test_metadata_manager.py
tests/scheduler/test_rule_extractor.py

Refactor metadata manager. User need to commit the transaction using commit function

Refactor metadata manager

---

ai_flow/common/util/db_util/session.py
ai_flow/metadata/util.py
ai_flow/model/internal/contexts.py
ai_flow/model/operator.py
ai_flow/model/workflow.py
ai_flow/scheduler/rule_executor.py
ai_flow/scheduler/runtime_context.py
ai_flow/scheduler/schedule_command.py
tests/scheduler/test_rule_executor.py

Add rule executor

---

ai_flow/__init__.py
ai_flow/common/configuration/config_constants.py
ai_flow/common/configuration/config_templates/aiflow_server.yaml
ai_flow/task_executor/kubernetes/__init__.py
ai_flow/task_executor/kubernetes/helpers.py
ai_flow/task_executor/kubernetes/k8s_task_executor.py
ai_flow/task_executor/kubernetes/kube_config.py
ai_flow/task_executor/kubernetes/kube_scheduler.py
ai_flow/task_executor/kubernetes/kube_watcher.py
ai_flow/task_executor/kubernetes/pod_generator.py
ai_flow/task_executor/kubernetes/pod_template_file_sample/pod_template.yaml
tests/task_executor/kubernetes/__init__.py
tests/task_executor/kubernetes/base_pod.yaml
tests/task_executor/kubernetes/pod_for_deserialize.yaml
tests/task_executor/kubernetes/test_helpers.py
tests/task_executor/kubernetes/test_k8s_task_executor.py
tests/task_executor/kubernetes/test_kube_config.py
tests/task_executor/kubernetes/test_kube_scheduler.py
tests/task_executor/kubernetes/test_kube_watcher.py
tests/task_executor/kubernetes/test_pod_generator.py

Add k8s task executor
- Add k8s task executor

Add k8s task executor

---

ai_flow/common/configuration/config_constants.py
ai_flow/model/status.py
ai_flow/scheduler/workflow_executor.py
tests/scheduler/test_workflow_executor.py

Add workflow executor

---

ai_flow/model/internal/events.py
ai_flow/scheduler/scheduling_event_processor.py
tests/scheduler/test_scheduling_event_processor.py

Add scheduling event processor

Add scheduling event processor

---

ai_flow/scheduler/dispatcher.py
ai_flow/scheduler/scheduling_unit.py
ai_flow/scheduler/worker.py
tests/scheduler/test_dispatcher.py

Add dispatcher

---

ai_flow/scheduler/timer.py
tests/scheduler/test_dispatcher.py
tests/scheduler/test_rule_executor.py
tests/scheduler/test_rule_extractor.py
tests/scheduler/test_scheduling_event_processor.py
tests/scheduler/test_timer.py
tests/scheduler/test_utils.py
tests/scheduler/test_workflow_executor.py

refactor scheduler tests.

---

ai_flow/metadata/metadata_manager.py
ai_flow/model/internal/conditions.py
ai_flow/model/internal/events.py
ai_flow/model/status.py
ai_flow/scheduler/scheduling_event_processor.py
ai_flow/task_executor/kubernetes/kube_watcher.py
tests/metadata/test_metadata_manager.py
tests/model/test_status.py
tests/scheduler/test_scheduling_event_processor.py

Add scheduling events

---

ai_flow/common/configuration/config_constants.py
ai_flow/metadata/metadata_manager.py
ai_flow/model/internal/events.py
ai_flow/model/operator.py
ai_flow/model/rule.py
ai_flow/scheduler/rule_executor.py
ai_flow/scheduler/scheduler.py
ai_flow/scheduler/scheduling_event_processor.py
ai_flow/scheduler/worker.py
ai_flow/scheduler/workflow_executor.py
tests/metadata/test_metadata_manager.py
tests/model/test_workflow.py
tests/scheduler/test_dispatcher.py
tests/scheduler/test_rule_executor.py
tests/scheduler/test_rule_extractor.py
tests/scheduler/test_scheduler.py
tests/scheduler/test_scheduling_event_processor.py
tests/scheduler/test_utils.py
tests/scheduler/test_worker.py
tests/scheduler/test_workflow_executor.py

Add Scheduler Worker

---

ai_flow/task_executor/common/task_executor_base.py
tests/task_executor/common/test_task_executor_base.py

Fix schedule command

---

ai_flow/common/util/time_utils.py
ai_flow/metadata/metadata_manager.py
ai_flow/rpc/client/aiflow_client.py
ai_flow/rpc/client/util/proto_to_meta.py
ai_flow/rpc/server/server.py
ai_flow/rpc/service/scheduler_service.py
ai_flow/rpc/service/util/meta_to_proto.py
ai_flow/scheduler/dispatcher.py
ai_flow/scheduler/rule_extractor.py
ai_flow/scheduler/scheduler.py
ai_flow/scheduler/scheduling_event_processor.py
ai_flow/scheduler/timer.py
tests/common/util/test_time_utils.py
tests/metadata/test_metadata_manager.py
tests/rpc/test_metadata_service.py
tests/rpc/test_task_execution_operations.py
tests/rpc/test_workflow_execution_operations.py
tests/rpc/test_workflow_operations.py
tests/rpc/test_workflow_schedule_operations.py
tests/rpc/test_workflow_trigger_operations.py
tests/scheduler/test_dispatcher.py
tests/scheduler/test_rule_executor.py
tests/scheduler/test_rule_extractor.py
tests/scheduler/test_scheduler.py
tests/scheduler/test_timer.py
tests/scheduler/test_utils.py
tests/scheduler/test_worker.py
tests/test_utils/mock_utils.py

Supporting periodic tasks

---

.gitignore
ai_flow/cli/commands/task_manager_command.py
ai_flow/model/operators/python.py
ai_flow/task_executor/local/worker.py
docs/content/get_started/quickstart/locally.md
docs/content/installation.md
requirements.txt
tests/model/operators/test_python_operator.py

Add docs about quickstart demo

---

docs/content/get_started/quickstart/locally.md

Fix the doc

---

docs/content/deployment/overview.md
docs/content/get_started/quickstart/locally.md
docs/content/installation/index.md
docs/content/installation/installing_from_pypi.md
docs/content/installation/installing_from_sources.md
requirements.txt
setup.py

Add Installation from sources docs

---

docs/content/get_started/quickstart/locally.md
docs/content/installation/installing_from_pypi.md
docs/index.rst

Fix documentation formats

---

ai_flow/common/util/process_utils.py
ai_flow/common/util/string_utils.py
ai_flow/operators/flink/__init__.py
ai_flow/operators/flink/flink_operator.py
ai_flow/operators/spark/spark_submit.py
ai_flow/task_executor/local/worker.py
docs/content/installation/installing_from_sources.md
samples/flink_operator/flink_run_example.py
tests/common/util/test_string_utils.py
tests/operators/flink/__init__.py
tests/operators/flink/test_flink_operator.py
tests/operators/spark/test_spark_submit.py

Add Flink Operator
- Move string utils from SparkSubmitOperator
- Improve docs about installing from source code
- Add Flink Operator

Flink operator

---

.coveragerc
.dockerignore
pom.xml
tests/metadata/test_metadata_manager.py
tests/rpc/test_namespace_rpc.py
tests/rpc/test_task_execution_rpc.py
tests/rpc/test_workflow_execution_rpc.py
tests/rpc/test_workflow_rpc.py
tests/rpc/test_workflow_schedule_rpc.py
tests/rpc/test_workflow_snapshot_rpc.py
tests/rpc/test_workflow_trigger_rpc.py

Fix unittests about existed namespace

Fix unittests about existed namespace

---

docs/content/concepts.md

Add docs about concepts

---

README.md
docs/content/get_started/about.md

Update the introduction section and provide the link to the existing article in README.

Update the introduction section in README

---

ai_flow/common/util/file_util/zip_file_util.py
ai_flow/model/operator.py
ai_flow/notification/notification_client.py
ai_flow/rpc/service/util/response_wrapper.py
docs/content/concepts/operators.md
docs/content/get_started/quickstart/in_docker.md
docs/content/get_started/quickstart/locally.md
docs/content/operation/index.md

Improve some docs and logging

---

.github/workflows/ai_flow_cd.yml
.github/workflows/publish_ai_flow_image.yaml
lib/notification_service/setup.py
setup.py

Daily uploading packages to PyPI

---

ai_flow/common/configuration/config_templates/aiflow_server.yaml
ai_flow/rpc/service/scheduler_service.py
ai_flow/task_executor/common/heartbeat_manager.py
docker-compose.yaml
docs/content/get_started/quickstart/in_docker.md
docs/content/get_started/quickstart/locally.md
docs/content/how_to_guides/set_up_mysql_as_backend.md
docs/content/installation/installing_from_pypi.md
docs/content/operation/deploying_aiflow_server.md
docs/content/plugins/blob_manager_plugin.md
docs/reference/extra_packages.md
lib/notification_service/requirements.txt
requirements.txt
samples/quickstart/quickstart_workflow.py

Improve documentations
